
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 17 08:09:13 EDT 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 7;
  public static final int MULOP = 6;
  public static final int ADDOP = 5;
  public static final int error = 1;
  public static final int LPAR = 2;
  public static final int SEMI = 4;
  public static final int RPAR = 3;
  public static final int EOF = 0;
}

